//! Structs for formatting and parsing DAIS-ribosome output in TSV format, as
//! well as functions to write the entire TSV files from ribosome [`outputs`].
//!
//! For writing TSV output, the [`Writers`] type is provided which can be used
//! with [`write_product_output`] and [`write_genome_output`]. These functions
//! take [`RibosomeOutput`] and automatically handle materializing the outputs
//! and formatting the TSV records.
//!
//! For parsing TSV files, a dedicated parser (implementing [`Iterator`]) is
//! provided for each file type.
//!
//! For more fine-grained control, each of the six files has an owned struct
//! (useful for parsing) and a view struct (useful for writing without
//! re-allocating).
//!
//! [`outputs`]: crate::outputs
//! [`RibosomeOutput`]: crate::outputs::RibosomeOutput
//! [`write_product_output`]: Writers::write_product_output
//! [`write_genome_output`]: Writers::write_genome_output

mod del_file;
mod gen_del_file;
mod gen_ins_file;
mod gen_seq_file;
mod ins_file;
mod seq_file;
mod writing;

pub use del_file::*;
pub use gen_del_file::*;
pub use gen_ins_file::*;
pub use gen_seq_file::*;
pub use ins_file::*;
pub use seq_file::*;
pub use writing::*;

use serde::{Deserialize, Deserializer};
use std::fmt::Display;
use zoe::prelude::{AminoAcids, AminoAcidsView, Len, Nucleotides, NucleotidesView};

/// The representation of null in HADOOP, used to represent empty sequences or
/// missing data in DAIS-ribosome.
const HADOOP_NULL: &str = "\\N";

/// A wrapper type for a nullable field.
///
/// When parsed via [`Deserialize`], a value of [`HADOOP_NULL`] is automatically
/// converted into an empty string. When displayed, empty types instead display
/// [`HADOOP_NULL`].
pub(crate) struct Nullable<T>(pub(crate) T);

impl<'de> Deserialize<'de> for Nullable<String> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>, {
        let val = String::deserialize(deserializer)?;

        if val == HADOOP_NULL {
            Ok(Self(String::new()))
        } else {
            Ok(Self(val))
        }
    }
}

impl<T> Display for Nullable<T>
where
    T: NullableValue + Display,
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        if self.is_null() {
            f.write_str(HADOOP_NULL)
        } else {
            write!(f, "{}", self.0)
        }
    }
}

/// A formatter generated by [`Nullable::display_null_or_else`], which either
/// displays [`HADOOP_NULL`] if the value is empty, or calls a closure on the
/// contained data to determine what to display.
pub(crate) struct NullOrElseFormatter<'a, T, F> {
    /// The nullable value to potentially display.
    val:     &'a Nullable<T>,
    /// The closure for mapping a non-null value to a displayable type.
    or_else: F,
}

impl<T, F, H> Display for NullOrElseFormatter<'_, T, F>
where
    T: NullableValue,
    F: Fn(&T) -> H,
    H: Display,
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self.val.as_option() {
            Some(val) => write!(f, "{}", (self.or_else)(val)),
            None => write!(f, "{HADOOP_NULL}"),
        }
    }
}

/// A trait unifying the types of values that can be contained in [`Nullable`].
pub(crate) trait NullableValue: Sized {
    /// The value mapping to [`HADOOP_NULL`], typically equivalent to
    /// [`Default::default`].
    const NULL: Self;

    /// Returns whether the value should be treated as [`NULL`].
    ///
    /// [`NULL`]: NullableValue::NULL
    fn is_null_value(&self) -> bool;
}

impl<T: NullableValue> Nullable<T> {
    /// A null instance of [`Nullable`], which will be displayed as
    /// [`HADOOP_NULL`].
    const NULL: Self = Nullable(T::NULL);

    /// Returns whether the contained value is null or not.
    pub fn is_null(&self) -> bool {
        self.0.is_null_value()
    }

    /// Returns the nullable field as an [`Option`], where null is `None`.
    pub fn as_option(&self) -> Option<&T> {
        (!self.is_null()).then_some(&self.0)
    }

    /// Converts the nullable field into an [`Option`], where null is `None`.
    pub fn into_option(self) -> Option<T> {
        (!self.is_null()).then_some(self.0)
    }

    /// Displays [`HADOOP_NULL`] if a null value is contained, otherwise
    /// transforms the contained value into a displayable type with closure `f`.
    pub fn display_null_or_else<F, H>(&self, f: F) -> NullOrElseFormatter<'_, T, F>
    where
        F: Fn(&T) -> H,
        H: Display, {
        NullOrElseFormatter {
            val:     self,
            or_else: f,
        }
    }
}

impl<T: NullableValue> Default for Nullable<T> {
    fn default() -> Self {
        Self::NULL
    }
}

impl NullableValue for String {
    const NULL: Self = String::new();

    fn is_null_value(&self) -> bool {
        self.is_empty()
    }
}

impl NullableValue for &str {
    const NULL: Self = "";

    fn is_null_value(&self) -> bool {
        self.is_empty()
    }
}

impl NullableValue for Nucleotides {
    const NULL: Self = Nucleotides::new();

    fn is_null_value(&self) -> bool {
        self.is_empty()
    }
}

impl NullableValue for AminoAcids {
    const NULL: Self = AminoAcids::new();

    fn is_null_value(&self) -> bool {
        self.is_empty()
    }
}

impl NullableValue for NucleotidesView<'_> {
    const NULL: Self = NucleotidesView::new();

    fn is_null_value(&self) -> bool {
        self.is_empty()
    }
}

impl NullableValue for AminoAcidsView<'_> {
    const NULL: Self = AminoAcidsView::new();

    fn is_null_value(&self) -> bool {
        self.is_empty()
    }
}

impl<T> NullableValue for &[T] {
    const NULL: Self = &[];

    fn is_null_value(&self) -> bool {
        self.is_empty()
    }
}
