[workspace]
members = ["crates/ribosome", "crates/ribosome-cli"]
resolver = "2"

[workspace.package]
version = "2.0.0"
edition = "2024"
authors = ["Samuel S. Shepard", "William Chettleburgh"]
rust-version = "1.96"

[workspace.dependencies]
zoe = { version = "0.0.30", default-features = false, features = [
    "multiversion",
    "rand",
] }

[profile.dev]
opt-level = 1

[profile.prod]
inherits = "release"
codegen-units = 1
lto = "fat"
strip = true
