[package]
name = "dais-ribosome"
version = "2.0.0"
edition = "2024"

[features]
default = ["regression-testing"]
regression-testing = []

[dependencies]
clap = { version = "4", features = ["derive"] }
rayon = "1"
toml = "1.1"
serde = "1"
serde_derive = "1"

zoe = { version = "0.0.28", default-features = false, features = [
    "multiversion",
    "rand",
] }
sha1_smol = "1"
md5 = "0.8"
getrandom = "0.4"
jiff = "0.2.18"

[[bin]]
bench = false
path = "src/main.rs"
name = "ribosome"
