#!/bin/bash

# Filename:         ribosome
# Description:      Protein annotation engine for influenza and SC2.
#
# Date dedicated:   2022-07-20
# Author:           Samuel S. Shepard, Centers for Disease Control and Prevention
#
# Citation:         Unpublished
#
# =============================================================================
#
#                            PUBLIC DOMAIN NOTICE
#
#  This source code file or script constitutes a work of the United States
#  Government and is not subject to domestic copyright protection under 17 USC §
#  105. This file is in the public domain within the United States, and
#  copyright and related rights in the work worldwide are waived through the CC0
#  1.0 Universal public domain dedication:
#  https://creativecommons.org/publicdomain/zero/1.0/
#
#  The material embodied in this software is provided to you "as-is" and without
#  warranty of any kind, express, implied or otherwise, including without
#  limitation, any warranty of fitness for a particular purpose. In no event
#  shall the Centers for Disease Control and Prevention (CDC) or the United
#  States (U.S.) government be liable to you or anyone else for any direct,
#  special, incidental, indirect or consequential damages of any kind, or any
#  damages whatsoever, including without limitation, loss of profit, loss of
#  use, savings or revenue, or the claims of third parties, whether or not CDC
#  or the U.S. government has been advised of the possibility of such loss,
#  however caused and on any theory of liability, arising out of or in
#  connection with the possession, use or performance of this software.
#
#  Please provide appropriate attribution in any work or product based on this
#  material.

shopt -s nullglob

# UTILITY FUNCTIONS #
function help() {
    cat << EOL

Usage:

        ribosome                            help
                                            install (explicit)
                    [--module <MODULE>]	    rebuild
                    [--module <MODULE>]	    <†fasta|*tab> [<output1.seq> <output2.ins> <output3.del> [<output_file3.gen**] ]

        †if classified, fasta:  >ID|type_segment[_subtype]
        *if classified, tab:    ID<TAB>type_segment_[subtype]<TAB>sequence

        ** Also procduces output4.gen.ins and output5.gen.del if specified

        Valid modules: INFLUENZA, BETACORONAVIRUS, RSV

EOL
    cleanup
    exit 0
}

IFX_PROG=RIBOSOME
owd=$(pwd)
function cleanup() {
    rm -rf "$workdir"
}

function catglob() {
    local glob=""
    for glob in "$@"; do
        # nullglob will take of expansion
        # shellcheck disable=SC2086
        if test -n "$(echo $glob)"; then
            cat $glob
        fi
    done
}

#######################

#tab=$'\t'
bpath=
if [ "$bpath" == "" ]; then
    bpath=$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)
fi
libp=$bpath/lib
source "$bpath/bin/utils.sh"

function install() {
    local repo=$1
    local namespace=${2:-"flu-informatics"}
    local server=${3:-"git.biotech.cdc.gov"}
    local pinned_tag="R1.7.1"
    if [ "$repo" == "sswsort" ]; then
        pinned_tag="v1.6.3"
    fi

    if [ "$repo" == "sampling" ]; then
        pinned_tag="R1.7.0"
    fi

    cd "$libp" || die "Bad directory $libp"

    if [ ! -d "$repo" ]; then
        git clone "https://${server}/${namespace}/${repo}.git" > /dev/null \
            || die "failed to install $repo"
    fi
    git -C "$libp/$repo" checkout $pinned_tag > /dev/null 2>&1 \
        || die "failed to checkout $repo $pinned_tag"
}

function script_path() {
    local repo=$1
    local script=$2
    local namespace=${3:-"flu-informatics"}

    if [ -x "$libp/$repo/$script" ]; then
        echo -n "$libp/$repo/$script"
    elif command -v "$script" > /dev/null 2>&1; then
        echo -n "$(which "$script")"
    elif [ -x "$bpath/../$repo/$script" ]; then
        echo -n "$bpath/../$repo/$script"
    else
        install "$repo" "$namespace" > /dev/null \
            && echo -n "$libp/$repo/$script" \
            || die "Could not assign $repo/$script"
    fi
}

# Select dependencies
function set_scripts() {
    SSWSORT=$(script_path sswsort SSWSORT)
    partitionByField=$(script_path sampling partitionByField.pl)
    reviseTaxa=$(script_path editMSA reviseTaxa.pl)
    codonCorrectStats=$(script_path editMSA codonCorrectStats.pl)
    stripSequences=$(script_path editMSA stripSequences.pl)
    sam2fasta=$(script_path convert sam2fasta.pl)
    delim2fasta=$(script_path convert delim2fasta.pl)
    fa2delim=$(script_path convert fa2delim.pl)
    nt2aa=$(script_path convert nt2aa.pl)
}

# Create working path
workdir_prefix=${IFX_WORK_DIR:-"$bpath/workdir"}
workdir=$(mktemp -d "$workdir_prefix"/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX)
[ -d "$workdir" ] \
    && TOKEN=$(basename "$workdir") \
    || die "Could not create working directory under $bpath"

# files and vars
binp=$bpath/bin
refp=$bpath/refs
specp=$bpath/spec
nullp="$workdir"/2-unused
alnp="$workdir"/3-alignment
protp="$workdir"/4-translation
module=INFLUENZA

case $1 in
    -m | --module)
        if [ "$2" ]; then
            module="$2"
            shift
        fi
        shift
        ;;
esac

# programs
command -v uname > /dev/null 2>&1 && OS=$(uname -s)
if [ "$OS" != "Linux" ] && [ "$OS" != "Darwin" ]; then
    time_stamp "Your $OS OS not yet supported."
    exit 0
fi
SSW="$binp"/third_party/ssw_$OS
[[ "$OS" == "Linux" ]] && SSW+="_$(uname -m)"
PARALLEL="$binp/third_party/parallel --will-cite"
BASH=bash
LIMIT_SSW=500                             # threshold before grid
SINGLE_LOCAL_PROCS=${IFX_LOCAL_PROCS:-16} # local processes on executing node
GRID_PROCS=${IFX_GRID_PROCS:-80}          # grid array processes
GRID_ON=${IFX_GRID_DEF:-0}                # yes, we can use the cluster if needed, default off

if [ "$1" == "help" ] || [ "$#" -eq "0" ]; then
    help
elif [ "$1" == "install" ]; then
    time_stamp "Installing and checking paths as needed"
    set_scripts && cat << EOL
    SSWSORT             $SSWSORT
    partitionByField    $partitionByField
    reviseTaxa          $reviseTaxa
    codonCorrectStats   $codonCorrectStats
    stripSequences      $stripSequences
    sam2fasta           $sam2fasta
    delim2fasta         $delim2fasta
    fa2delim            $fa2delim
    nt2aa               $nt2aa
EOL
    finish "Done"
elif [ "$1" == "rebuild" ]; then
    time_stamp "rebuilding references"
    [ -d "$refp/$module" ] && rm -rf "$refp/${module:?}"
    mkdir "$refp/$module"

    partitionByField=$(script_path sampling partitionByField.pl)
    "$partitionByField" "$specp/${module}.refs" -F 2 "$refp/$module/"
    if test -n "$(echo "$refp/$module"/*.refs)"; then
        for ref in "$refp/$module"/*.refs; do
            segment=$(basename "$ref" .refs)
            mkdir "$refp/$module/$segment" \
                || die "Could not make directory: $segment"
            "$partitionByField" "$ref" -F 1 "$refp/$module/$segment/" \
                && rm "$ref"
        done
    fi
    finish "rebuilt"

elif [ "$#" -eq "4" ] || [ "$#" -eq "5" ]; then
    INPUT_FILE=$1
    OUT_SEQ=$2
    OUT_INS=$3
    OUT_DEL=$4
    if [ "$#" -eq "5" ]; then
        OUT_GEN=$5
    else
        OUT_GEN=""
    fi
elif [ "$#" -eq "1" ]; then
    INPUT_FILE=$1
    OUT_SEQ="$owd"/${TOKEN}.seq
    OUT_INS="$owd"/${TOKEN}.ins
    OUT_DEL="$owd"/${TOKEN}.del
else
    help
fi

# installl or set scripts
set_scripts

# if it's a pipe or not zero length, process it
if [ -p "$INPUT_FILE" ] || [ -s "$INPUT_FILE" ]; then
    cat "$INPUT_FILE" > "$workdir"/0-raw
    INPUT_FILE="$workdir"/0-raw
else
    rm -rf "$workdir"
    die "file '$INPUT_FILE' could not be read."
fi

ext=$("$binp"/ext.pl "$INPUT_FILE" "${module:-INFLUENZA}")
fastaresult="$workdir"/1-${TOKEN}.fa
annotresult="$workdir"/1-${TOKEN}.txt
coordresult="$workdir"/5-${TOKEN}.coords
insertresult="$workdir"/${TOKEN}.ins
seqresult="$workdir"/${TOKEN}.seq
genresult="$workdir"/${TOKEN}.genome

time_stamp "started, processing data"
if [ "$ext" == "unk" ]; then
    die "unknown input format"
elif [ "$ext" == "atxt" ]; then
    "$delim2fasta" "$INPUT_FILE" > "$fastaresult"
elif [ "$ext" == "afa" ]; then
    mv "$INPUT_FILE" "$fastaresult"
else
    if [ "$ext" == "txt" ]; then
        "$delim2fasta" "$INPUT_FILE" > "$fastaresult"
    elif [ "$ext" == "fa" ]; then
        mv "$INPUT_FILE" "$fastaresult"
    else
        die "unexpected format error: $ext"
    fi

    if [ "${module:-INFLUENZA}" == "BETACORONAVIRUS" ]; then
        preset=cov-beta
    elif [ "${module:-INFLUENZA}" == "RSV" ]; then
        preset=rsv
    else
        preset=flu-ABCD90P
    fi

    N=$(grep '>' "$fastaresult" -c)
    [ "${N:-0}" -eq "0" ] && die "only $N samples found in $fastaresult"

    time_stamp "performing GENETYPE annotations on $N sequences" \
        && "$SSWSORT" "$preset" "$fastaresult" "$annotresult" \
        && time_stamp "performed SSWSORT annotations with ${preset}." \
        || die "SSWSORT failure"

    [ -s "$annotresult" ] \
        && "$binp"/revcompIDs.pl "$fastaresult" <(cut -f3- "$annotresult") --in-place --strand-field

    "$reviseTaxa" -I -p -A <(cut -f3-4 "$annotresult") "$fastaresult" \
        || die "failed to revise annotations"
fi

# could de-duplicate
# need to check corrections: trimfile=$bpath/corrections/${prefix}.fa

function alignSpliceTranslate() {
    local alignp=$1
    local proteinp=$2
    local unusedp=$3
    local refPath=$4
    local queryDB=$5
    local module=$6
    local name=$module
    local script=$alignp/${name}
    local doGrid=0
    local n=$(grep '>' "$queryDB" -c)

    # Do we have sequences?
    [ "${n:-0}" -eq "0" ] && die "No sequences found ($n), exiting"
    [ ! -d "$alignp" ] && mkdir "$alignp"
    [ ! -d "$proteinp" ] && mkdir "$proteinp"
    [ ! -d "$unusedp" ] && mkdir "$unusedp"

    # Check for qsub
    if [ "$GRID_ON" -eq "1" ]; then
        if ! command -v qsub > /dev/null 2>&1; then
            time_stamp "No 'qsub' command found, switching to local computation."
            GRID_ON=0
        fi
    fi

    # perform initial estimate
    if [ "$n" -gt "$LIMIT_SSW" ] && [ "${GRID_ON:-0}" -eq "1" ]; then
        doGrid=1
        procs=$GRID_PROCS
    elif [ "$n" -ge "$SINGLE_LOCAL_PROCS" ]; then
        procs="$SINGLE_LOCAL_PROCS"
    else
        procs=1
    fi
    local samples=$((n / procs))
    [ "${samples:-0}" -lt "1" ] && samples=1

    ###
    cat > "${script}.sh" << EOL
#!/bin/bash
set -o pipefail
LANG=$LANG
shopt -u nocaseglob;shopt -u nocasematch

function die() { local t=\$(date +"%Y-%m-%d %k:%M:%S");echo -e "[\$t] $PROG/SSW ERROR \$1" 1>&2 && exit 1; }
function finish() { local t=\$(date +"%Y-%m-%d %k:%M:%S");echo -e "[\$t] $PROG/SSW :: \$1" && exit 0; }

perl -e 'use Digest::MD5;' >/dev/null 2>&1 || die "Missing Perl modules Digest::MD5 on \$(hostname), use yum to install."
perl -e 'use Digest::SHA;' >/dev/null 2>&1 || die "Missing Perl modules Digest::SHA on \$(hostname), use yum to install."

if [ "\$#" -eq "1" ];then
	ID=\$(printf %04d \$1)
else
	ID=\$(printf %04d \$SGE_TASK_ID)
fi

QUERY=$alignp/*.\$ID.fa
GENE=\$(basename \$QUERY .\$ID.fa)
REFP=$refPath/\$GENE
SSW_OPTS=\$("$binp"/getSSWconfig.pl $specp/${module}.ssw \$GENE)
[ ! -d "\$REFP" ] && mv \$QUERY $unusedp/ && exit 0

if test -n "\$(shopt -s nullglob;echo \$REFP/*.refs)";then
	for REF in \$REFP/*.refs;do
		SPEC=\$(basename \$REF .refs)
		PREFIX=$alignp/\$SPEC.\$GENE.\$ID
		SAM=\$PREFIX.sam

		"$binp"/chewToStart.pl -R \$REF \$QUERY \\
            | $SSW \$SSW_OPTS -s -h -c \$REF /dev/stdin 2> /dev/null \\
            | "$binp"/winnowSAM.pl /dev/stdin > \$SAM \\
		    && "$sam2fasta" -H \$SPEC -P \$REF \$SAM \$PREFIX -E -M \$QUERY \\
		    && "$binp"/makeProducts.pl \$PREFIX.fasta $specp/${module}.spec \$PREFIX -G \$GENE -R \$SPEC \\
		    && "$binp"/makeInsProducts.pl \$PREFIX.ins.txt $specp/${module}.spec \$PREFIX -G \$GENE -R \$SPEC \\
		    && "$codonCorrectStats" -S $specp/${module}.sto -F 3,4 -I \$PREFIX.ins -O \$PREFIX.ins.c \$PREFIX.products > \$PREFIX.products.c \\
		    && PREFIX2=$proteinp/\$SPEC.\$GENE.\$ID \\
		    && "$binp"/amendInsertionTable.pl -U \$PREFIX.ins.c -A \$PREFIX2 \\
		    && "$nt2aa" -U \$PREFIX2.products.c.tmp --right-pad-cds -T -E -M -P \$PREFIX.products.c | "$fa2delim" -A -B -I <(cut -f1,2,4 \$PREFIX2.ins) > \$PREFIX2.aa \\
            && mv \$PREFIX2.products.c.tmp \$PREFIX.products.c \\
		    && "$fa2delim" \$PREFIX.products.c --show-if-insertion --show-shift-indel -A --nt-id -B -I <(cat \$PREFIX.ins.c) > \$PREFIX2.cds \\
            || { echo -e "Environment:\n\t\$(hostname)\n\t\$(which perl)"; env|grep PERL|perl -pe 's/^/\t/'; exit 2; }
	done
else
	die "skipping \$GENE, missing refs"
fi
EOL
    # Insertions.
    # - sam2fasta produces `.ins.txt` which is the inserts of the sequence post
    #   `chewToStart` (also used by coord mapping to calculate oriOffset).
    #
    # - codonCorrectStats produces `ins.c` (used by untranslated products and
    #   coord mapping)
    #
    # - amendInsertiontable produces `.ins` (used by translated
    #   products, filters small frameshifts and NNN)
    #
    # - filterUntranslatedInserts filters out inserts that are outside of the
    #   translated CDS region.
    ###

    # ASSEMBLE on grid vs local
    chmod 755 "${script}.sh"
    local workdir=$alignp
    "$partitionByField" -L ${samples:-1} -G -F 2 "$queryDB" "$workdir"/
    procs=$(find "$workdir"/ -maxdepth 1 -name "*.????.fa" | wc -l)
    if [ "$doGrid" -eq "1" ]; then
        # intentional possible expansion
        # shellcheck disable=SC2086
        qsub $IRMA_QUEUE -t "1-$procs:1" -N "N$name" -sync y -wd "$workdir" -j y -o "${script}.o" "${script}.sh" > /dev/null 2>&1 \
            || {
                cat "$script.o"
                time_stamp "qsub of 'N$name' failed. Switching to master node."
                $PARALLEL --halt now,fail=1 --workdir "$workdir" -j "$SINGLE_LOCAL_PROCS" $BASH "${script}.sh" {} ::: $(seq "$procs") > "${script}.o" \
                    || {
                        cat "$script.o"
                        return 1
                    }
            }
    else
        $PARALLEL --halt now,fail=1 --workdir "$workdir" -j "$SINGLE_LOCAL_PROCS" $BASH "${script}.sh" {} ::: $(seq "$procs") > "${script}.o" 2>&1 \
            || {
                cat "$script.o"
                return 1
            }
    fi
    cat "$script.o"
}

time_stamp "removing extraneous FASTA characters" \
    && "$stripSequences" "$fastaresult" '*: .~-' > "${fastaresult}.tmp" \
    && mv "${fastaresult}.tmp" "$fastaresult" \
    && time_stamp "aligning, splicing products, and translating sequences" \
    && alignSpliceTranslate "$alnp" "$protp" "$nullp" "$refp/$module" "$fastaresult" "$module" \
    || die "SSW failed"

if test -n "$(echo "$nullp"/*.fa)"; then
    time_stamp "no specification yet for: $(for i in "$nullp"/*.fa; do basename "$i" .fa; done | cut -f1 -d'.' | tr '\n' ' ')"
fi

if test -n "$(echo "$alnp"/*.products.c)"; then
    time_stamp "mapping CDS and query coordinates"
    "$binp"/annotateCDS.pl "$specp/${module}.spec" "$fastaresult" \
        <(catglob "$alnp"/*.products.c) <(catglob "$alnp"/*.ins.c) \
        <(catglob "$alnp"/*.fasta) <(catglob "$alnp"/*.ins.txt) > "$coordresult" \
        || die "annotation failed"
fi
catglob "$protp"/*.ins | "$binp"/filterUntranslatedInserts.pl "$coordresult" /dev/stdin | tr '|' "\t" > "$insertresult"

if test -n "$(echo "$protp"/*.aa)"; then
    "$binp"/leftjoin.pl <(cat "$protp"/*.aa) <(cat "$protp"/*.cds) "$coordresult" | tr '|' "\t" > "${seqresult}"
fi

if test -n "$(echo "$nullp"/*.fa)"; then
    "$binp"/unused2delim.pl -F 14 <(cat "$nullp"/*.fa) >> "$seqresult"
fi

if [ "${OUT_GEN:-NONE}" != "NONE" ]; then
    if test -n "$(echo "$alnp"/*.????.fasta)"; then
        "$fa2delim" -Z -A -B --nt --show-if-insertion <(cat "$alnp"/*.????.fasta) -I <(cat "$alnp"/*.????.ins.txt) \
            | tr '|' "\t" > "$genresult"
        cat "$alnp"/*.????.ins.txt | tr '|' "\t" > "${genresult}.ins"
    fi
fi

# Produce output and clean up
[ -s "$genresult" ] \
    && mv "${genresult}.ins" "${OUT_GEN}.ins" \
    && "$binp"/seq2del.pl "$genresult" -G > "${OUT_GEN}.del" \
    && mv "$genresult" "$OUT_GEN"

[ -r "$seqresult" ] \
    && "$binp"/seq2del.pl "$seqresult" > "$OUT_DEL" \
    && mv "$seqresult" "$OUT_SEQ"

[ -r "$insertresult" ] \
    && mv "$insertresult" "$OUT_INS"

finish "finished"
