[[module]]
name = "flu"
version = "2.0-alpha"
references = "flu-references.fasta"
weights = "flu-codon-position-weights.tsv"
cds_spec = "flu-cds-spec.tsv"
alignment_method = "one-pass"

[module.formatting]
right_pad_aa = false
right_pad_cds = true

[module.rules]
list_contig_stop_extension = true
chew_to_start = true
repairable_end_limit = 9

[module.alignment]
default = { match = 14, mismatch = -1, gap_open = 40, gap_extend = 1 }
B_HA = { match = 10, mismatch = -1, gap_open = 50, gap_extend = 1 }

[[module]]
name = "cov"
references = "cov-references.fasta"
weights = "cov-codon-position-weights.tsv"
cds_spec = "cov-cds-spec.tsv"
alignment_method = "three-pass"

[module.formatting]
right_pad_aa = false
right_pad_cds = true

[module.rules]
chew_to_start = true
repairable_end_limit = 9

[module.alignment]
default = { match = 1, mismatch = -1, gap_open = 8, gap_extend = 1 }

[[module]]
name = "rsv"
references = "rsv-references.fasta"
weights = "rsv-codon-position-weights.tsv"
cds_spec = "rsv-cds-spec.tsv"
alignment_method = "three-pass"

[module.formatting]
right_pad_aa = false
right_pad_cds = true

[module.rules]
chew_to_start = true

[module.alignment]
default = { match = 1, mismatch = -1, gap_open = 10, gap_extend = 1 }
