[package]
name = "dais-ribosome-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

[[bin]]
name = "ribosome"
path = "main.rs"
doc = false

[dependencies]
sswsort = { git = "https://github.com/CDCgov/sswsort.git", tag = "v2.2.5" }
zoe = { workspace = true }
dais-ribosome = { path = "../ribosome" }
clap = { version = "4", features = ["derive"] }
rayon = "1"
num_cpus = "1"
getrandom = "0.4"
jiff = "0.2"
